[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap <C-_> <Plug>(caw:i:toggle)
  vmap <C-_> <Plug>(caw:i:toggle)
'''

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo =  'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-e>'
  let g:user_emmet_settings={ 'lang' : 'ja' }
'''

[[plugins]]
repo = 'mattn/webapi-vim'

### Color scheme
[[plugins]]
repo = 'tomasr/molokai'

### Languages Support ###
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:vim_markdown_folding_disabled=1
'''

[[plugins]]
repo = 'naberon/vim-cakehtml'
hook_add = '''
  autocmd BufNewFile,BufRead *.ctp set filetype=htmlcake
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'groenewege/vim-less'

