[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
hook_add = '''
  noremap <silent> ,df :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
  noremap <silent> ,db :<C-u>Denite buffer   -highlight-mode-insert=Search<CR>
  noremap <silent> ,dg :<C-u>Denite grep     -highlight-mode-insert=Search<CR>
  noremap <silent> ,dl :<C-u>Denite line     -highlight-mode-insert=Search<CR>
  noremap <silent> ,dy :<C-u>Denite neoyank  -highlight-mode-insert=Search<CR>
  noremap <silent> ,dm :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
'''
hook_post_source = '''
  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

### Languages Support ###
[[plugins]]
repo = 'sheerun/vim-polyglot'
add_hook = '''
  let g:polyglot_disabled = ['markdown']
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:vim_markdown_folding_disabled=1
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  let g:go_fmt_command = 'goimports'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

