[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
  nmap <C-_> <Plug>(caw:i:toggle)
  vmap <C-_> <Plug>(caw:i:toggle)
'''

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
  let g:neomake_python_enabled_makers = ['python', 'flake8']
  let g:neomake_javascript_enabled_makers = ['eslint']
  let g:neomake_go_enabled_malers = ['golint', 'govet']

  let g:neomake_error_sign = {'text': '✖', 'texthl': 'Repeat'}
  let g:neomake_warning_sign = {'text': '⚠', 'texthl': 'QuickFixLine'}
'''

[[plugins]]
repo = "benjie/neomake-local-eslint.vim"

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
\   '_' : {
\     'outputter/buffer/close_on_empty' : 1
\   }
\ }
'''

[[plugins]]
repo =  'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-e>'
  let g:user_emmet_settings={ 'lang' : 'ja' }
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

### Color scheme
[[plugins]]
repo = 'tomasr/molokai'

### Statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
\   'colorscheme': 'wombat'
\ }
'''
