[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
add_hook = '''
let g:polyglot_disabled = ['markdown']
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
" Layout - down / up / left / right
let g:fzf_layout = { 'down': '~40%' }

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" Override Files command to include dotfiles
command! -bang -nargs=? -complete=dir Files
\ call fzf#vim#files(<q-args>, { 'source': 'ag --hidden --ignore .git -g ""' }, <bang>0)

" Key mapping
nnoremap ,f  :Files<CR>
nnoremap ,gf :GFiles<CR>
nnoremap ,b  :Buffers<CR>
nnoremap ,ag :Ag<CR>
'''

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
let g:neomake_python_enabled_makers = ['python', 'flake8']
let g:neomake_javascript_enabled_makers = ['eslint']

let g:neomake_error_sign = {'text': 'X', 'texthl': 'Repeat'}
let g:neomake_warning_sign = {'text': '!', 'texthl': 'QuickFixLine'}
'''

[[plugins]]
repo = "benjie/neomake-local-eslint.vim"

[[plugins]]
repo = 'vim-scripts/surround.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
let g:netrw_nogx = 1
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
depends = 'open-browser.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

### Color scheme
[[plugins]]
repo = 'tomasr/molokai'

### Statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = { 'colorscheme': 'wombat' }
'''
